// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WindFarm.Api.Data;

#nullable disable

namespace WindFarm.Api.Migrations
{
    [DbContext(typeof(WindFarmDbContext))]
    partial class WindFarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WindFarm.Api.Data.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId", "Ts");

                    b.HasIndex("Status", "Severity", "Ts");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WindFarm.Api.Data.Entities.OperatorAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId", "Ts");

                    b.ToTable("OperatorActions");
                });

            modelBuilder.Entity("WindFarm.Api.Data.Entities.TelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AmbientTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("BladePitch")
                        .HasColumnType("double precision");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("NacelleDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerOutput")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<double>("RotorSpeed")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId", "Ts");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("WindFarm.Api.Data.Entities.Turbine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turbines");
                });
#pragma warning restore 612, 618
        }
    }
}
